version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: daria-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - vuejs:/app
    depends_on:
      - "back-end"
      - "front-end"
    networks:
      - daria-network

  front-end:
    container_name: daria-fe
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - vuejs:/app
    networks:
      - daria-network

  back-end:
    container_name: daria-be
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/config/.env
    ports: ['3005:3005']
    volumes:
      - '/src/node_modules'
    depends_on:
      - "db"
    networks:
      - daria-network

  db:
    container_name: daria-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: daria
      MONGO_INITDB_ROOT_PASSWORD: 9WuANDrLg25BJhPM
      MONGO_INITDB_DATABASE: daria
    ports: ["27017:27017"]
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - daria-network

networks:
  daria-network:
    driver: bridge

volumes:
  mongodb_data_container:
  vuejs:
